### ISSUE TITLE
메뉴바 아이콘 이슈

### ISSUE THREAD

**Issue by hatemogi** [hatemogi/Starworks#1]
애플리케이션 아이콘 적용했습니다. 캄솨! 합니다.

<img width="766" alt="2017-02-27 4 40 16" src="https://cloud.githubusercontent.com/assets/238582/23352600/91ec9b0e-fd0b-11e6-9e32-0de54e912736.png">

메뉴바 아이콘에는 흑백으로 적용하라고 해서, 흑백으로 사이즈를 줄여서 적용해 보았습니다.

선택했을 때의 모습입니다.

<img width="509" alt="2017-02-27 4 39 48" src="https://cloud.githubusercontent.com/assets/238582/23352596/8bf24e9c-fd0b-11e6-94eb-494907f27ac5.png">

선택하지 않았을 때의 모습입니다.

<img width="422" alt="2017-02-27 4 39 55" src="https://cloud.githubusercontent.com/assets/238582/23352599/8fffc226-fd0b-11e6-97ed-c75a4a08492d.png">

참고해주세요~!

**Comment by drdonny** [comment]
확인했습니다. 👍🏻
